# Generated by Django 2.1 on 2018-10-30 06:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 30, 6, 43, 16, 28631, tzinfo=utc)),
        ),
    ]
