# Generated by Django 2.1 on 2018-10-30 12:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20181030_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 30, 12, 24, 49, 843770, tzinfo=utc)),
        ),
    ]
