# Generated by Django 2.1 on 2018-10-30 13:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20181030_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 30, 13, 19, 45, 970691, tzinfo=utc)),
        ),
    ]
