# Generated by Django 2.1 on 2018-11-01 03:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20181101_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 1, 3, 3, 49, 753327, tzinfo=utc)),
        ),
    ]
