# Generated by Django 2.1 on 2018-11-03 08:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20181102_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=200)),
                ('image', models.ImageField(upload_to='event_pics')),
                ('time', models.DateTimeField(default=datetime.datetime(2018, 11, 3, 8, 36, 49, 923408, tzinfo=utc))),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='PastEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=200)),
                ('image', models.ImageField(upload_to='event_pics')),
                ('time', models.DateTimeField(default=datetime.datetime(2018, 11, 3, 8, 36, 49, 923408, tzinfo=utc))),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
