# Generated by Django 2.1 on 2018-11-03 09:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20181103_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futureevent',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 3, 9, 51, 35, 944187, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pastevent',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 3, 9, 51, 35, 944187, tzinfo=utc)),
        ),
    ]
