# Generated by Django 2.1 on 2018-11-04 03:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20181103_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futureevent',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 4, 3, 24, 0, 413864, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pastevent',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 4, 3, 24, 0, 411865, tzinfo=utc)),
        ),
    ]
