# Generated by Django 2.1 on 2018-11-05 13:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20181104_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futureevent',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 5, 13, 9, 38, 39828, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pastevent',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 5, 13, 9, 38, 39828, tzinfo=utc)),
        ),
    ]
