# Generated by Django 2.1 on 2018-11-05 20:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_auto_20181106_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futureevent',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
