# Generated by Django 2.1 on 2018-10-29 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_image', models.ImageField(upload_to='rooms_pics')),
                ('room_name', models.CharField(max_length=200)),
                ('room_about', models.TextField()),
                ('room_tv', models.CharField(choices=[('NONE', 'None'), ('FLAT TV', 'Flat TV'), ('FLAT LED TV', 'Flat Led TV')], default='NONE', max_length=20)),
                ('room_wifi', models.CharField(choices=[('NOT AVAILABLE', 'Not Available'), ('AVAILABLE', 'Available')], default='NOT AVAILABLE', max_length=20)),
                ('room_ac', models.CharField(choices=[('NOT AVAILABLE', 'Not Available'), ('AVAILABLE', 'Available')], default='NOT AVAILABLE', max_length=30)),
                ('room_bedroom', models.IntegerField(choices=[(1, 'Single Bed'), (2, 'Double Bed'), (3, 'Three Beds')], default=1)),
                ('room_bathroom', models.CharField(choices=[('ATTACHED', 'Attached'), ('NOT ATTACHED', 'Not Attached')], default='ATTACHED', max_length=30)),
            ],
        ),
    ]
