# Generated by Django 2.1 on 2018-10-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_image_title', models.CharField(max_length=200)),
                ('upload_image', models.ImageField(upload_to='gallery_upload_pics')),
            ],
        ),
    ]
