# Generated by Django 2.1 on 2018-11-05 13:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_gallery_gallery_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryuploads',
            options={'ordering': ['-upload_date']},
        ),
        migrations.AddField(
            model_name='galleryuploads',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 5, 13, 9, 38, 55450, tzinfo=utc)),
        ),
    ]
