# Generated by Django 2.1 on 2018-11-05 13:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20181105_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryuploads',
            name='upload_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 5, 13, 40, 55, 229491, tzinfo=utc)),
        ),
    ]
