# Generated by Django 2.1 on 2018-10-30 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='messsage',
            new_name='message',
        ),
    ]
