# Generated by Django 2.1 on 2018-11-05 13:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='service',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 11, 5, 13, 40, 55, 151369, tzinfo=utc)),
        ),
    ]
