# Generated by Django 2.1 on 2018-11-05 19:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20181105_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 11, 5, 19, 49, 4, 290631, tzinfo=utc)),
        ),
    ]
