# Generated by Django 2.1 on 2018-10-29 10:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(default=datetime.datetime(2018, 10, 29, 16, 36, 42, 60878))),
                ('check_out', models.DateField(default=datetime.datetime(2018, 10, 30, 16, 36, 42, 60878))),
                ('adult', models.PositiveIntegerField(default=3)),
                ('child', models.PositiveIntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.RoomDetail')),
            ],
        ),
    ]
